version: '3.8'

services:
  gradio-app:
    build:
      context: .
      dockerfile: Dockerfile-gradio
    ports:
      - "7860:7860"
    depends_on:
      - annoy-db

  annoy-db:
    build:
      context: .
      dockerfile: Dockerfile-annoy
    ports:
      - "5000:5000"
